### ISSUE TITLE
 Can I run nfstream with pf_ring_zc?

### ISSUE THREAD

**Issue by frkn4129** [nfstream/nfstream#117]
Is nfstream compatible with pf_ring? Does nfstream support this?

**Comment by aouinizied** [comment]
@frkn4129 This is technically possible with an adequate integration within the native code part of nfstream but we are not working on it. Current plans are as follows:

*  Work on improving nfstream overall performance.
* DPDK integration instead of PFRING_ZC to avoid commercial license.

 If you want to contribute by adding PFRING_ZC capabilities to NFStream, do not hesitate to push a PR.
