### ISSUE TITLE
Wrong value of Flow ID when making a new plugin

### ISSUE THREAD

**Issue by zujany** [nfstream/nfstream#142]
**Describe the bug**
I want to make a plugin using the flow ID, but I'm getting the following string "NFEvent.FLOW", instead of the expected value ID.  
I tried to append it as int and string, and I got the same results.

**To Reproduce**

```
from nfstream import NFStreamer
from nfstream import NFPlugin

class FlowID(NFPlugin):
    def on_init(self, packet, flow):
        flow.udps.packetsID=[]
        flow.udps.packetsID.append(str(flow.id))
    def on_update(self, packet, flow):
        flow.udps.packetsID.append(str(flow.id))
    def on_expire(self, flow):
        flow.udps.packetsID.append(str(flow.id))

if __name__ == "__main__":
    nfstreamer = NFStreamer(source="test.pcap", udps=[FlowID()]).to_pandas()
    print(nfstreamer[['udps.packetsID']])
```

**Expected behavior**
 udps.packetsID
0     0,0,0,0,...
1     1,1,1,1,...
2     2,2,2,2,...
...                                                 .

**Obtained behavior**
 udps.packetsID
0     ['NFEvent.FLOW', 'NFEvent.FLOW', 'NFEvent.FLOW...
1      ['NFEvent.FLOW', 'NFEvent.FLOW', 'NFEvent.FLOW']
2     ['NFEvent.FLOW', 'NFEvent.FLOW', 'NFEvent.FLOW...
3     ['NFEvent.FLOW', 'NFEvent.FLOW', 'NFEvent.FLOW...
4     ['NFEvent.FLOW', 'NFEvent.FLOW', 'NFEvent.FLOW...
...                                                 ...

**Desktop**
 - OS: Ubuntu 20.04.2 LTS
 - Python 3.8.10 
 - NFStream version 6.5.1

**Comment by aouinizied** [comment]
@zujany Thanks for reporting. However, this behavior is a design choice.
nfstream uses multiprocessing for performance reasons. Consequently, The streamer is the drivers process that pulls expired flows from meters processes (workers/pushers where all the flow computation happens). 
`id` generation is maintained within the streamer to guarantee it's consistency across meters.

Additionally, NFPlugin entry points are in a flow life cycle, that's why we do not need to verify or access this attribute.

Zied
