### ISSUE TITLE
Can I get the specific packet data of each stream?

### ISSUE THREAD

**Issue by 0eteam** [nfstream/nfstream#32]

**Comment by aouinizied** [comment]
@0eteam this is possible using NFPlugin.

**Comment by 0eteam** [comment]
Where can I get the appropriate API  to call or case program?Thanks a lot.

**Comment by drnpkr** [comment]
Try the flow slicer example here: https://www.nfstream.org/docs/api#nfplugin

**Comment by MainRo** [comment]
in the on_update method of a plugin, you can get the ip payload from the ip_packet field of packet.

**Comment by 0eteam** [comment]
Now that I've got the packets, how do I sort them by streaming mode?
Is there a feature id in the program？ Or can I only identify it through  (SRC_IP, SRC_port, DST_IP, DST_port, Protocol)?

**Comment by drnpkr** [comment]
Yes and yes. There is an ID for each flow detected by NFStream. Since NFStream is an IP Flow metering tool, packets are organized into flow entries based on the well-known 5-tuple (source and destination IPs and port numbers, and the protocol) as per your observation. The precise name of these parameters are provided in the API documentation: https://www.nfstream.org/docs/api

If you understand your goal correctly, you already have one packet flows. So hypothetically you can group them in other ways too. Certainly, it is not recommended as this way you will experience performance degradation. But if you just want to quickly test your approach while working on a proof of concept, it might do the trick for you.

**Comment by 0eteam** [comment]
In the file of flow.py ,the code "self.id = -1", the id of the packet is also not updated in the NFStreamer.
for example:
init: -1
updata: -1
updata: -1
updata: -1
updata: -1
init: -1

**Comment by drnpkr** [comment]
> In the file of flow.py ,the code "self.id = -1", the id of the packet is also not updated in the NFStreamer.
> for example:
> init: -1
> updata: -1
> updata: -1
> updata: -1
> updata: -1
> init: -1

Oeteam, I honestly do not understand what you mean by this. No offence, but I cannot read your thoughts. You have to be more specific when describing your problem. You can make a reference to the specific line in the code. The outputs are coming from where? Did you implement flow slicer as a plugin? Did you use a typical example?

**Comment by 0eteam** [comment]
Limited by my expression and technical level, I am very sorry for not being able to express my thoughts clearly, but I have solved most of the problems. Now I use your model to test my thoughts. Thank you very much for your contribution and help. (^_^)

**Comment by drnpkr** [comment]
Glad to hear!

**Comment by aouinizied** [comment]
@0eteam once you are called within a Plugin you are called for each packet within a single flow so no need to check the id of the flow. What you see with -1 values is normal behavior as the identifier is updated later in the driver process to ensure consistency across parallel meters.
I think an example of your code could help us to understand your needs and your use case and give you more help if needed.
