### ISSUE TITLE
Update numpy dependency

### ISSUE THREAD

**Issue by SoerenBusse** [nfstream/nfstream#61]
**Describe the bug**
Hey there,

nfstream requires numpy <= 1.18.5, which breaks some other dependencies like tensorflow, which requires at least version 1.19.2.

Is there a reason why nfstream is relying on an old nfstream version? In our quick test it seems to works absolutely fine with 1.20.2. Would it be possible to update the dependency?

**Comment by aouinizied** [comment]
@SoerenBusse  Numpy released a version (don't remember exactly the version number) that had issues running using Pypy3. In order to fix it we forced numpy version in NFStream requirements. As now I see that such an issue is fixed. We are able to update it (https://github.com/nfstream/nfstream/commit/cf0b7a1c80195a2a7278fcaf28d2680664964d75). I will release a patch that includes updated requirements. Thanks for reporting.

Zied

**Comment by aouinizied** [comment]
Fixed and released in v6.3.1.

Zied
